name: NuageProject

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
        - opened
        - synchronize

permissions:
  contents: read
  packages: write

jobs:
  check-service:
    name: Check Service
    # Will run on every pull and push request
    if: github.event_name == 'pull_request' || github.event_name == 'push' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
            python-version: '3.12'

      - name: Install dependencies
        run: uv sync

      - name: Build
        run: uv build

      - name: Test
        run: uv run pytest tests/
      
  build_docker_image:
    name: Build Docker Image
    # Will run on every push request
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref, event=branch
            type=sha,
            type=raw, value=latest
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
